//
//  DifferenceOfStrings.swift
//  SwiftAGDS
//
//  Created by Guilherme Wahlbrink on 2019-04-11.
//  Copyright © 2019 Guilherme Wahlbrink. All rights reserved.
//

/*
 Given two strings s and t which consist of only lowercase letters.
 
 String t is generated by random shuffling string s and then add one more letter at a random position.
 
 Find the letter that was added in t.
 
 Example:
 
 Input:
 s = "abcd"
 t = "abcde"
 
 Output:
 e
 
 Explanation:
 'e' is the letter that was added.
 */

import Foundation

func findTheDifference(_ s: String, _ t: String) -> Character {
    var sumS = 0
    var sumT = 0
    
    for i in s {
        sumS += Int(i.asciiValue!)
    }
    
    for i in t {
        sumT += Int(i.asciiValue!)
    }
    return Character(UnicodeScalar(sumT - sumS)!)
}

// version for leetCode
func findTheDifference2(_ s: String, _ t: String) -> Character {
    var sumS = 0
    var sumT = 0
    
    for i in s {
        sumS += Int(UnicodeScalar(String(i))!.value)
    }
    
    for i in t {
        sumT += Int(UnicodeScalar(String(i))!.value)
    }
    return Character(UnicodeScalar(sumT - sumS)!)
}
